version: '3.3'

services:
  authenticationService:
    depends_on:
      - authentication_db
    image: authentication:latest
    restart: always
    ports:
      - 9090:9090
    environment:
      SERVER_PORT: 9090
      MYSQL_HOST: authentication_db
      
  authentication_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authentication_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  shipmentService:
    depends_on:
      - shipment_db
    image: shipment:latest
    restart: always
    ports:
      - 9091:9091
    environment:
      SERVER_PORT: 9091
      MYSQL_HOST: shipment_db
      APP_SAMPLESERVICE: "http://sampleService:9092"
      APP_BIOBANKSERVICE: "http://biobankService:9093"
  
  shipment_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipment_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  
  sampleService:
    depends_on:
      - sample_db
    image: sample:latest
    restart: always
    ports:
      - 9092:9092
    environment:
      SERVER_PORT: 9092
      MYSQL_HOST: sample_db
      APP_USERSERVICE: "http://authenticationService:9090"
      APP_SHIPMENTSERVICE: "http://shipmentService:9091"
      APP_BIOBANKSERVICE: "http://biobankService:9093"
      APP_DONORSERVICE: "http://donorService:9095"
  
  sample_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  biobankService:
    depends_on:
      - biobank_db
    image: biobank:latest
    restart: always
    ports:
      - 9093:9093
    environment:
      SERVER_PORT: 9093
      MYSQL_HOST: biobank_db

  biobank_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biobank_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  donorService:
    depends_on:
      - donor_db
    image: donor:latest
    restart: always
    ports:
      - 9095:9095
    environment:
      SERVER_PORT: 9095
      MYSQL_HOST: donor_db

  donor_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donor_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      
  sprecsampleService:
    depends_on:
      - sprecsample_db
    image: sprecsample:latest
    restart: always
    ports:
      - 9094:9094
    environment:
      SERVER_PORT: 9094
      MYSQL_HOST: sprecsample_db

  sprecsample_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sprecsample_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  