apiVersion: v1
kind: ConfigMap
metadata:
  name: biobank-mysql-config # arbitrary name
  namespace: biobanksprec
data: # the actual contents - key-value pairs
  mysql-url: biobank-db-service # service we're going to creare for mongdb application
  initdb.sql: |
    -- MySQL dump 10.13  Distrib 5.7.38, for Linux (x86_64)
    --
    -- Host: localhost    Database: biobank_db
    -- ------------------------------------------------------
    -- Server version	5.7.38

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    --
    -- Table structure for table `biobanks`
    --

    DROP TABLE IF EXISTS `biobanks`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `biobanks` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `acronym` varchar(255) DEFAULT NULL,
      `contact_information` varchar(255) DEFAULT NULL,
      `country` varchar(255) DEFAULT NULL,
      `description` varchar(255) DEFAULT NULL,
      `juristic_person` varchar(255) DEFAULT NULL,
      `name` varchar(255) DEFAULT NULL,
      `url` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `biobanks`
    --

    --
    -- Table structure for table `document_types`
    --

    DROP TABLE IF EXISTS `document_types`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `document_types` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `document_types`
    --

    --
    -- Table structure for table `documents`
    --

    DROP TABLE IF EXISTS `documents`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `documents` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `created_at` varchar(255) DEFAULT NULL,
      `deleted_at` varchar(255) DEFAULT NULL,
      `file_name` varchar(255) DEFAULT NULL,
      `guid` varchar(255) DEFAULT NULL,
      `object_id` int(11) DEFAULT NULL,
      `size` int(11) DEFAULT NULL,
      `updated_at` varchar(255) DEFAULT NULL,
      `type_id` int(11) NOT NULL,
      PRIMARY KEY (`id`),
      KEY `FKcaosxk6vnuhcwvhh6j1g8nv93` (`type_id`),
      CONSTRAINT `FKcaosxk6vnuhcwvhh6j1g8nv93` FOREIGN KEY (`type_id`) REFERENCES `document_types` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `documents`
    --

    --
    -- Table structure for table `freezers`
    --

    DROP TABLE IF EXISTS `freezers`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `freezers` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `created_at` datetime(6) DEFAULT NULL,
      `deleted_at` datetime(6) DEFAULT NULL,
      `name` varchar(255) NOT NULL,
      `parent_id` int(11) DEFAULT NULL,
      `updated_at` datetime(6) DEFAULT NULL,
      `room_id` int(11) NOT NULL,
      PRIMARY KEY (`id`),
      KEY `FK77of7axaxt116376vc4iqgxsi` (`room_id`),
      CONSTRAINT `FK77of7axaxt116376vc4iqgxsi` FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `freezers`
    --

    --
    -- Table structure for table `opts`
    --

    DROP TABLE IF EXISTS `opts`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `opts` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(255) NOT NULL,
      `value` bigint(20) NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `opts`
    --

    --
    -- Table structure for table `rooms`
    --

    DROP TABLE IF EXISTS `rooms`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `rooms` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `created_at` datetime(6) DEFAULT NULL,
      `deleted_at` datetime(6) DEFAULT NULL,
      `name` varchar(255) NOT NULL,
      `updated_at` datetime(6) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `rooms`
    --

    /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

    -- Dump completed on 2022-07-17 14:17:41
    INSERT INTO `biobanks` (`id`, `acronym`, `name`, `url`, `juristic_person`, `country`, `contact_information`, `description`)
    VALUES
      (1, 'BIOBANK ACRONYM','BIOBANK NAME','BIOBANK  URL','BIOBANK  JURISTIC PERSON','BIOBANK COUNTRY','{}','BIOBANK DESCRIPTION');

    INSERT INTO `document_types` (`id`, `name`)
    VALUES
      (1,'Shipment'),
      (2,'Consent'),
      (3,'Clinical');

    INSERT INTO `documents` (`id`, `object_id`, `file_name`, `size`, `GUID`, `type_id`, `deleted_at`, `created_at`, `updated_at`)
    VALUES
      (1,1,'eeee',123002.00,'02CB717FCB2AB4C4C873FCC09A5EE19A',1,NULL,'2019-08-08 13:25:10','2019-08-08 13:25:10');

    INSERT INTO `rooms` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`)
    VALUES
      (1,'Room 1',NULL,NULL,NULL),
      (2,'Room 2',NULL,NULL,NULL);

    /*INSERT INTO `opts` (`id`, `name`, `value`)
    VALUES
      (1,'biobank_director','BIOBANK DIRECTOR');
    */
    INSERT INTO `freezers` (`id`, `room_id`, `name`, `parent_id`, `created_at`, `updated_at`, `deleted_at`)
    VALUES
      (1,1,'Freezer 1', NULL, NULL, NULL, NULL),
      (2,1,'Freezer 2', NULL, NULL, NULL, NULL),
      (3,1,'Division 1', 1, NULL, NULL, NULL),
      (4,1,'Division 2', 1, NULL, NULL, NULL),
      (5,1,'Drawer 1', 3, NULL, NULL, NULL),
      (6,1,'Drawer 2', 3, NULL, NULL, NULL),
      (7,1,'Slot 1', 5 , NULL, NULL, NULL),
      (8,1,'Slot 2', 5, NULL, NULL, NULL),
      (9,1,'Slot 3', 5, NULL, NULL, NULL),
      (10,1,'Slot 1', 6, NULL, NULL, NULL),
      (11,1,'Slot 2',6, NULL, NULL, NULL),
      (12,1,'Slot 3',6, NULL, NULL, NULL);