apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  # echo -n text | base64
  mysql-user: YWRtaW4=      # admin
  mysql-password: YWRtaW4=  # admin
  mysql-root-pwd: cm9vdA==  # root