apiVersion: v1
kind: ConfigMap
metadata:
  name: donor-mysql-config # arbitrary name
  namespace: biobanksprec # è lo stesso namespace da utilizzare nei service
data: # the actual contents - key-value pairs
  mysql-url: donor-db-service # service we're going to creare for mongdb application
  initdb.sql: |
    -- MySQL dump 10.13  Distrib 5.7.38, for Linux (x86_64)
    --
    -- Host: localhost    Database: donor_db
    -- ------------------------------------------------------
    -- Server version	5.7.38

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    --
    -- Table structure for table `consents`
    --

    DROP TABLE IF EXISTS `consents`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `consents` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `consent_details` varchar(255) DEFAULT NULL,
      `created_at` varchar(255) DEFAULT NULL,
      `deleted_at` varchar(255) DEFAULT NULL,
      `updated_at` varchar(255) DEFAULT NULL,
      `user_id` int(11) DEFAULT NULL,
      `contact_id` int(11) NOT NULL,
      `donor_id` int(11) NOT NULL,
      PRIMARY KEY (`id`),
      KEY `FKqhhjx5i29389od9hbmfddg1fu` (`contact_id`),
      KEY `FKnskec24u4kdhlphs0apaphlu3` (`donor_id`),
      CONSTRAINT `FKnskec24u4kdhlphs0apaphlu3` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`),
      CONSTRAINT `FKqhhjx5i29389od9hbmfddg1fu` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `consents`
    --

    --
    -- Table structure for table `contacts`
    --

    DROP TABLE IF EXISTS `contacts`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `contacts` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `address` varchar(255) DEFAULT NULL,
      `birth_date` date DEFAULT NULL,
      `born_city` varchar(255) DEFAULT NULL,
      `country` varchar(255) DEFAULT NULL,
      `created_at` date DEFAULT NULL,
      `deleted_at` date DEFAULT NULL,
      `email` varchar(255) DEFAULT NULL,
      `first_name` varchar(255) DEFAULT NULL,
      `identification_number` varchar(255) DEFAULT NULL,
      `last_name` varchar(255) DEFAULT NULL,
      `phone` varchar(255) DEFAULT NULL,
      `resident_at` varchar(255) DEFAULT NULL,
      `sex` varchar(255) DEFAULT NULL,
      `updated_at` date DEFAULT NULL,
      `zip` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `contacts`
    --

    --
    -- Table structure for table `donor_clinicals`
    --

    DROP TABLE IF EXISTS `donor_clinicals`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `donor_clinicals` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `clinic_informations` varchar(255) DEFAULT NULL,
      `created_at` varchar(255) DEFAULT NULL,
      `donor_desease` varchar(255) DEFAULT NULL,
      `other_informations` varchar(255) DEFAULT NULL,
      `updated_at` varchar(255) DEFAULT NULL,
      `donor_id` int(11) NOT NULL,
      PRIMARY KEY (`id`),
      KEY `FKfbi77ena1ogqvikoffdspbm7s` (`donor_id`),
      CONSTRAINT `FKfbi77ena1ogqvikoffdspbm7s` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `donor_clinicals`
    --

    --
    -- Table structure for table `donors`
    --

    DROP TABLE IF EXISTS `donors`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `donors` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `birth_date` datetime(6) DEFAULT NULL,
      `collected_data` varchar(255) DEFAULT NULL,
      `contact_information` int(11) DEFAULT NULL,
      `created_at` datetime(6) DEFAULT NULL,
      `death_cause` varchar(255) DEFAULT NULL,
      `death_date` datetime(6) DEFAULT NULL,
      `deleted_at` datetime(6) DEFAULT NULL,
      `ethnic_group` varchar(255) DEFAULT NULL,
      `first_name` varchar(255) DEFAULT NULL,
      `identification_number` varchar(255) DEFAULT NULL,
      `last_name` varchar(255) DEFAULT NULL,
      `random_id` varchar(255) DEFAULT NULL,
      `sex` varchar(255) DEFAULT NULL,
      `survey_data` varchar(255) DEFAULT NULL,
      `updated_at` datetime(6) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `donors`
    --

    --
    -- Table structure for table `miabis_ethnic_groups`
    --

    DROP TABLE IF EXISTS `miabis_ethnic_groups`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `miabis_ethnic_groups` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `miabis_ethnic_groups`
    --

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

    -- Dump completed on 2022-07-17 14:16:01

    INSERT INTO `donors` (`id`, `random_id`, `first_name`, `last_name`, `identification_number`, `birth_date`, `sex`, `collected_data`, `survey_data`, `ethnic_group`, `death_date`, `death_cause`, `contact_information`, `created_at`, `updated_at`, `deleted_at`)
    VALUES
      (13,NULL,'Angela','Castiglione','CSTANG83H54C351H','1983-06-14','Female',NULL,NULL,'Caucasian',NULL,NULL,NULL,NULL,'2019-10-16 10:48:00','2019-10-16 10:48:00'),
      (14,'4030929677','','','4030929677',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-10-20 15:46:20',NULL),
      (15,'2560203490','','','2560203490',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-10-20 15:46:51',NULL),
      (16,NULL,'LIMO','ANGELO','ANGLNA90A35C385A','1990-06-13','Female',NULL,NULL,'Caucasian',NULL,NULL,NULL,NULL,'2020-11-02 12:06:25',NULL),
      (17,NULL,'Concordio','Trevisani','TRVCCO45A15A028B','1945-01-15','Male',NULL,NULL,'Caucasian',NULL,NULL,NULL,NULL,NULL,NULL),
      (18,NULL,'Geraldino','Rossi','RSSGER75C17C351H','1975-03-17','Male',NULL,NULL,'Caucasian',NULL,NULL,NULL,NULL,NULL,NULL),
      (19,'1447519318','ANONYMOUS','ANONYMOUS','1447519318',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2019-09-30 14:09:48','2019-09-30 14:09:48',NULL),
      (20,'1410873500','ANONYMOUS','ANONYMOUS','1410873500',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2019-09-30 14:17:36','2019-09-30 14:17:36',NULL),
      (21,'3121823405','ANONYMOUS','ANONYMOUS','3121823405',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2019-09-30 14:19:03','2019-09-30 14:19:03',NULL),
      (22,NULL,'CIAO','CIAO2','412211241','2019-12-31','Male',NULL,NULL,'African','2019-12-31',NULL,NULL,'2019-09-30 14:20:54','2019-09-30 14:20:54',NULL),
      (23,'3685959996','ANONYMOUS','ANONYMOUS','3685959996',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2019-10-02 14:57:19','2019-10-02 14:57:19',NULL),
      (24,NULL,'POIU','UIOP','123654','1111-12-12','Male',NULL,NULL,'Other','1115-12-12',NULL,NULL,'2019-10-02 14:58:10','2019-10-02 14:58:30',NULL),
      (25,NULL,'AAA','AAA','AAA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2019-10-02 15:30:19','2019-10-02 15:30:19',NULL),
      (26,'592461437','ANONYMOUS','ANONYMOUS','592461437',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2019-10-02 15:35:06','2019-10-02 15:35:06',NULL),
      (27,'369531264','ANONYMOUS','ANONYMOUS','369531264',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2019-10-03 14:11:53','2019-10-03 14:11:53',NULL),
      (28,'4157103709','ANONYMOUS','ANONYMOUS','4157103709',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2019-10-23 13:19:23','2019-10-23 13:19:23',NULL),
      (29,NULL,'BHJBK','FGVUFUKY','870707','2003-09-22','Male',NULL,NULL,'Other','2018-09-22','shot',NULL,'2019-10-23 13:23:14','2019-10-23 13:23:14',NULL),
      (30,NULL,'ALBERTO','LOBERTO','222',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-06-29 13:32:47','2020-06-29 13:32:47',NULL),
      (31,'812080032','','','812080032',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-10-20 15:47:23',NULL),
      (32,'881796460','','','881796460',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-10-20 15:48:04',NULL);

    INSERT INTO `miabis_ethnic_groups` (`id`, `name`)
    VALUES
      (1,'African'),
      (2,'Caucasian'),
      (3,'Pacific Islander'),
      (4,'East Asian'),
      (5,'Native American'),
      (6,'Other');

    INSERT INTO `donor_clinicals` (`id`, `donor_id`, `donor_desease`, `clinic_informations`, `other_informations`, `created_at`, `updated_at`)
    VALUES
      (1,22,'saexnhgiolsdfnh','dnvsdonasdfphjap','qwfnhfaspiophas','2019-09-30 14:21:55','2019-09-30 14:21:55'),
      (2,13,NULL,NULL,NULL,'2019-10-03 14:29:42','2019-10-03 14:29:42');

    INSERT INTO `contacts` (`id`, `first_name`, `last_name`)
    VALUES (1, 'Chris', 'Martin');

    INSERT INTO `consents` (`id`, `user_id`, `donor_id`, `contact_id`, `consent_details`, `created_at`, `updated_at`, `deleted_at`)
    VALUES
      (1,1,22,1,'{\"informFamily\": true, \"diagnosisPurposes\": true, \"shareDataResearch\": true, \"scientificResearch\": true, \"shareDataDiagnosis\": true, \"specialRequirements\": null}','2019-09-30 14:22:02','2019-09-30 14:22:02',NULL);
