apiVersion : apps/v1
kind: Deployment
metadata:
  name: donor-be
  namespace: biobanksprec # è lo stesso namespace da utilizzare nei service
  labels:
    app: donor-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donor-be
  template:
    metadata:
      labels:
        app: donor-be
    spec:
      # necessario se immagini private
      # imagePullSecrets:
      #   - name: acr-secret-cs
      containers:
        - name: donor-be
          image: khalld/donor:latest
          ports:
          - containerPort: 9095
          env:
          - name: 'SPRING_DATASOURCE_USERNAME'
            value: 'admin'
          - name: 'SPRING_DATASOURCE_PASSWORD'
            value: 'admin'
          - name: 'SERVER_PORT'
            value: '9095'
          - name: 'MYSQL_HOST'
          # TODO: devi mettere l'IP qua dentro del POD dove runna il database !!! (anche per aws)
            value: donor-db-service
          - name: 'KEYCLOAK_HOST'
            value: keycloak


          # oppure sovrascrivere l'intero record del db
          # - name: 'SPRING_DATASOURCE_URL'
          #   value: 'jdbc:mysql://192.168.50.75:3306/donor_db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC'
          #   # value: 'jdbc:mysql://10.1.0.96:3306/donor_db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC'