apiVersion : apps/v1
kind: Deployment
metadata:
  name: donor-be
  # namespace: donor # è lo stesso namespace da utilizzare nei service
  labels:
    app: donor-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donor-be
  template:
    metadata:
      labels:
        app: donor-be
    spec:
      # necessario se immagini private
      # imagePullSecrets:
      #   - name: acr-secret-cs
      containers:
        - name: donor-be
          image: khalld/donor:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9095
          env:
          - name: 'SPRING_DATASOURCE_USERNAME'
            value: 'admin'
          - name: 'SPRING_DATASOURCE_PASSWORD'
            value: 'admin'
          - name: 'SERVER_PORT'
            value: '9095'
          - name: 'SPRING_DATASOURCE_URL'
            # TODO: devi mettere l'IP qua dentro del POD dove runna il database !!!
            value: 'jdbc:mysql://10.1.0.134:3306/donor_db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC'
            # value: 'jdbc:mysql://10.1.0.96:3306/donor_db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC'