apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-mysql-config # arbitrary name
  namespace: biobanksprec
data: # the actual contents - key-value pairs
  mysql-url: sample-db-service # service we're going to creare for mongdb application
  initdb.sql: |
    -- MySQL dump 10.13  Distrib 5.7.38, for Linux (x86_64)
    --
    -- Host: localhost    Database: sample_db
    -- ------------------------------------------------------
    -- Server version	5.7.38

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    --
    -- Table structure for table `collections`
    --

    DROP TABLE IF EXISTS `collections`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `collections` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `acronym` varchar(255) DEFAULT NULL,
      `age_high` int(11) DEFAULT NULL,
      `age_low` int(11) DEFAULT NULL,
      `description` varchar(255) DEFAULT NULL,
      `name` varchar(255) DEFAULT NULL,
      `note` varchar(255) DEFAULT NULL,
      `age_unit_id` int(11) DEFAULT NULL,
      `material_type_id` int(11) DEFAULT NULL,
      `sex_id` int(11) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FKm31mt908cjah7ur1jfu4aii7i` (`age_unit_id`),
      KEY `FKewrin2xiqlcfsxxxyhtau4tx7` (`material_type_id`),
      KEY `FKnmrgx543ojjj7bdn1pag0n638` (`sex_id`),
      CONSTRAINT `FKewrin2xiqlcfsxxxyhtau4tx7` FOREIGN KEY (`material_type_id`) REFERENCES `miabis_material_type` (`id`),
      CONSTRAINT `FKm31mt908cjah7ur1jfu4aii7i` FOREIGN KEY (`age_unit_id`) REFERENCES `static_age_unit` (`id`),
      CONSTRAINT `FKnmrgx543ojjj7bdn1pag0n638` FOREIGN KEY (`sex_id`) REFERENCES `miabis_sex` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `collections`
    --

    --
    -- Table structure for table `collections_samples`
    --

    DROP TABLE IF EXISTS `collections_samples`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `collections_samples` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `collection_id` int(11) DEFAULT NULL,
      `sample_id` int(11) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FKfxa5dx5f90uyvo67sl5ay6p6r` (`collection_id`),
      KEY `FKor8gxuf0m6ajh32fcqgx2pwxq` (`sample_id`),
      CONSTRAINT `FKfxa5dx5f90uyvo67sl5ay6p6r` FOREIGN KEY (`collection_id`) REFERENCES `collections` (`id`),
      CONSTRAINT `FKor8gxuf0m6ajh32fcqgx2pwxq` FOREIGN KEY (`sample_id`) REFERENCES `sample` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `collections_samples`
    --

    --
    -- Table structure for table `miabis_material_type`
    --

    DROP TABLE IF EXISTS `miabis_material_type`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `miabis_material_type` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `definition` varchar(255) DEFAULT NULL,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `miabis_material_type`
    --

    --
    -- Table structure for table `miabis_quantities`
    --

    DROP TABLE IF EXISTS `miabis_quantities`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `miabis_quantities` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `unit_of_measure` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `miabis_quantities`
    --

    --
    -- Table structure for table `miabis_sex`
    --

    DROP TABLE IF EXISTS `miabis_sex`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `miabis_sex` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `definition` varchar(255) DEFAULT NULL,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `miabis_sex`
    --

    --
    -- Table structure for table `miabis_storage_temperature`
    --

    DROP TABLE IF EXISTS `miabis_storage_temperature`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `miabis_storage_temperature` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `definition` varchar(255) DEFAULT NULL,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `miabis_storage_temperature`
    --

    --
    -- Table structure for table `sample`
    --

    DROP TABLE IF EXISTS `sample`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `sample` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `anatomycal_site` varchar(255) DEFAULT NULL,
      `box_id` int(11) DEFAULT NULL,
      `consent_id` int(11) DEFAULT NULL,
      `donor_id` int(11) DEFAULT NULL,
      `location_id` varchar(255) DEFAULT NULL,
      `location_path` varchar(255) DEFAULT NULL,
      `parent_sample_id` varchar(255) DEFAULT NULL,
      `residual_quantity` float DEFAULT NULL,
      `sample_id` varchar(255) DEFAULT NULL,
      `sampled_time` varchar(255) DEFAULT NULL,
      `sampling_technique` varchar(255) DEFAULT NULL,
      `sprec` varchar(255) DEFAULT NULL,
      `user_id` int(11) DEFAULT NULL,
      `storage_temperature` int(11) DEFAULT NULL,
      `type_id` int(11) DEFAULT NULL,
      `um_id` int(11) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FK8ow47pyd865rvuqt1ltea1o1x` (`storage_temperature`),
      KEY `FKohlwo8qdfrhntiivmei40yqvl` (`type_id`),
      KEY `FKt0gneju1xc305684t1shkk30r` (`um_id`),
      CONSTRAINT `FK8ow47pyd865rvuqt1ltea1o1x` FOREIGN KEY (`storage_temperature`) REFERENCES `miabis_storage_temperature` (`id`),
      CONSTRAINT `FKohlwo8qdfrhntiivmei40yqvl` FOREIGN KEY (`type_id`) REFERENCES `sample_type` (`id`),
      CONSTRAINT `FKt0gneju1xc305684t1shkk30r` FOREIGN KEY (`um_id`) REFERENCES `miabis_quantities` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `sample`
    --

    --
    -- Table structure for table `sample_type`
    --

    DROP TABLE IF EXISTS `sample_type`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `sample_type` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `acronym` varchar(255) DEFAULT NULL,
      `denomination` varchar(255) DEFAULT NULL,
      `tipo` int(11) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `sample_type`
    --

    --
    -- Table structure for table `static_age_unit`
    --

    DROP TABLE IF EXISTS `static_age_unit`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `static_age_unit` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `static_age_unit`
    --

    /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

    -- Dump completed on 2022-07-17 14:11:08

    /*
    Insert static_age_unit records
    */
    INSERT INTO `static_age_unit` (`id`, `name`)
    VALUES (1,'Years'),(2,'Months'),(3,'Weeks'),(4,'Days');
    /*
        Insert miabis_quantities records
    */
    INSERT INTO `miabis_quantities` (`id`, `unit_of_measure`)
    VALUES (1,'ml'),(2,'l'),(3,'g'),(4,'mg');
    /*
        Insert miabis_sex records
    */
    INSERT INTO `miabis_sex` (`id`, `name`, `definition`)
    VALUES (1,'Male','Male.'),(2,'Female','Female.'),
      (3,'Unknown','A proper value is applicable but not known.'),
      (4,'Undifferentiated','Undifferentiated, the gender could not be uniquely identified such as hermaphrodite.');
    /*
        Insert miabis_material_type records
    */
    INSERT INTO `miabis_material_type` (`id`, `name`, `definition`)
    VALUES
      (1,'Blood','Blood that has not been separated into its various components; blood that has not been modified except for the addition of an anticoagulant.'),
      (2,'DNA','A long linear double-stranded polymer formed from nucleotides attached to a deoxyribose backbone and found in the nucleus of a cell; associated with the transmission of genetic information.'),
      (3,'Faeces','The material discharged from the bowel during defecation. It consists of undigested food, intestinal mucus, epithelial cells, and bacteria.'),
      (4,'Immortalized Cell Lines','Cells of a single type (human, animal, or plant) that have been adapted to grow continuously in the laboratory and are used in research.'),
      (5,'Isolated Pathogen','An isolated biological agent causing disease; a disease producer e.g. virus, bacterium, prion, other microorganism etc.'),
      (6,'Other','Any other type of material taken from a biological entity, e.g. amniotic fluid, cerebrospinal fluid (CSV), mitochondrial RNA.'),
      (7,'Plasma','Plasma is the fluid (acellular) portion of the circulating blood, as distinguished from the serum that is the fluid portion of the blood obtained by removal of the fibrin clot and blood cells after coagulation.'),
      (8,'RNA','One of two types of nucleic acid made by cells. RNA contains information that has been copied from DNA (the other type of nucleic acid). Cells make several different forms of RNA, and each form has a specific job in the cell.'),
      (9,'Saliva','A clear liquid secreted into the mouth by the salivary glands and mucous glands of the mouth; moistens the mouth and starts the digestion of starches.'),
      (10,'Serum','The clear portion of the blood that remains after the removal of the blood cells and the clotting proteins.'),
      (11,'Tissue (Frozen)','An anatomical structure consisting of similarly specialized cells and intercellular matrix, aggregated according to genetically determined spatial relationships, performing a specific function.'),
      (12,'Tissue (FFPE)','Tissue, formalin fixated and paraffin preserved or equivalent.'),
      (13,'Urine','The fluid that is excreted by the kidneys. It is stored in the bladder and discharged through the urethra.');

    /*
        Insert miabis_storage_temperature records
    */
    INSERT INTO `miabis_storage_temperature` (`id`, `name`, `definition`)
    VALUES
      (1,'RT','Room temperature'),
      (2,'2 °C to 10°C','Between 2 °C and 10 °C'),
      (3,'-18 °C to -35 °C','Between -18 °C and -35 °C'),
      (4,'-60 °C to -85 °C','Between -60 °C and -85 °C'),
      (5,'LN','Liquid Nitrogen, -150 °C to -196 °C'),
      (6,'Other','Any other temperature or long time storage information');
    /*
        Insert sample_type records
    */
    INSERT INTO `sample_type` (`id`, `tipo`, `denomination`, `acronym`)
    VALUES
      (1,0,'Ascites Fluid','ASC'),
      (2,0,'Amniotic Fluid','AMN'),
      (3,0,'Bronchoalveolar Lavage','BAL'),
      (4,0,'Blood (whole)','BLD'),
      (5,0,'Bone Marrow Aspirate','BMA'),
      (6,0,'Breast Milk','BMK'),
      (7,0,'Buccal Cells','BUC'),
      (8,0,'Unficolled buffy coat, viable','BUF'),
      (9,0,'Unficolled buffy coat, non viable','BFF'),
      (10,0,'Ficoll mononuclear cells, viable','CEL'),
      (11,0,'Fresh cells from nonblooc specimen type','CEN'),
      (12,0,'Cells from nonblood speciment type (e.g., ascites, amniotic) viable','CLN'),
      (13,0,'Cord Blood','CSF'),
      (14,0,'Cerebrospinal Fluid','CSF'),
      (15,0,'Enriched (physichochemically) circulating tumor cells','CTC'),
      (16,0,'Dried whole blood (e.g., Gunthrie cards)','DWB'),
      (17,0,'Nasal Washing','NAS'),
      (18,0,'Ficoll mononuclear cells, nonviable','PEL'),
      (19,0,'Cells from nonblood specimen type (e.g, ascites, amniotic) nonviable','PEN'),
      (20,0,'Pleural Fluid','PFL'),
      (21,0,'Dental Pulp','PLP'),
      (22,0,'Plasma, single spun','PL1'),
      (23,0,'Plasma, double spun','PL2'),
      (24,0,'Red blood cells','RBC'),
      (25,0,'Saliva','SAL'),
      (26,0,'Semen','SEM'),
      (27,0,'Serum','SER'),
      (28,0,'Sputum','SPT'),
      (29,0,'Stool','STL'),
      (30,0,'Synovial Fluid','SYN'),
      (31,0,'Tears','TER'),
      (32,0,'24h Urine','U24'),
      (33,0,'Urine, random (\"spot\")','URN'),
      (34,0,'Urine, first morning','URM'),
      (35,0,'Urine, timed','URT'),
      (36,0,'Other','ZZZ'),
      (37,1,'Bone','BON'),
      (38,1,'Fresh cells from nonblood specimen type (e.g., biopsy)','CEN'),
      (39,1,'Cells from nonblood specimen type (e.g., dissociated tissue), viable','CLN'),
      (40,1,'Cells from fine needle aspirate','FNA'),
      (41,1,'Hair','HAR'),
      (42,1,'Cells from lase capture microdissected tissue','LCM'),
      (43,1,'Nails','NAL'),
      (44,1,'Cells from nonblood specimen type (e.g., dissociated tissue), nonviable','PEN'),
      (45,1,'Placenta','PLC'),
      (46,1,'Solid Tissue','TIS'),
      (47,1,'Disrupted tissue, nonviable','TCM'),
      (48,1,'Teeth','TTH'),
      (49,1,'Other','ZZZ');

    /*
        Insert sample records
    */
    INSERT INTO `sample` (`id`, `user_id`, `box_id`, `donor_id`, `consent_id`, `sample_id`, `location_id`, `location_path`, `parent_sample_id`, `type_id`, `sprec`, `sampling_technique`, `storage_temperature`, `sampled_time`, `anatomycal_site`, `residual_quantity`, `um_id`)
    VALUES
      (1,1,NULL,30,NULL,'SA903F94462','9','Freezer 1/Division 1/Drawer 1/Slot 3',NULL,39,'CLN-A12-B-B-ACA-G-T',NULL,1,'2018-05-25 15:12:00',NULL,150.00,1),
      (2,1,NULL,NULL,NULL,'SC7D2A18B40','7','Freezer 1/Division 1/Drawer 1/Slot 1',NULL,38,'CEN-A06-B-B-ALL-B-D',NULL,1,'2019-08-08 09:00:00','ddd',NULL,1),
      (3,NULL,1,NULL,NULL,'SCB56E14484','7','Freezer 1/Division 1/Drawer 1/Slot 1',NULL,2,'AMN-ADD-J-N-N-J-N',NULL,NULL,NULL,NULL,NULL,1),
      (4,NULL,1,22,1,'S89A9AC7486','2','Freezer 2',NULL,39,NULL,'klòkokpèok',2,NULL,NULL,NULL,3),
      (5,NULL,1,NULL,NULL,'S8B94326D91',NULL,NULL,NULL,2,'AMN-ACD-N-J-N-J-N',NULL,NULL,NULL,NULL,NULL,NULL),
      (6,NULL,1,NULL,NULL,'SFB2CAB69B5',NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
      (7,1,NULL,NULL,NULL,'S73525269DD','2','Freezer 2',NULL,2,NULL,NULL,1,'2019-01-01 00:00:00',NULL,NULL,1),
      (8,1,NULL,24,NULL,'S82C2BF4479','2','Freezer 2',NULL,3,NULL,NULL,2,'2018-05-25 15:12:00',NULL,NULL,1),
      (9,1,NULL,25,NULL,'S956A6E8C82','2','Freezer 2',NULL,38,NULL,NULL,2,'2018-05-25 15:12:00',NULL,NULL,1),
      (10,1,NULL,26,NULL,'S64A719ECA1','2','Freezer 2',NULL,38,NULL,NULL,1,'2019-02-04 00:00:00',NULL,NULL,1),
      (11,1,NULL,NULL,NULL,'SC7F2017DE8','2','Freezer 2',NULL,38,NULL,NULL,5,'2019-01-01 00:01:00',NULL,NULL,1);

    /*
        Insert colletions records
    */
    INSERT INTO `collections` (`id`, `name`, `acronym`, `description`, `sex_id`, `age_low`, `age_high`, `age_unit_id`, `material_type_id`, `note`)
    VALUES
      (1,'prova',NULL,NULL,2,NULL,NULL,1,2,NULL),
      (2,'test','tst','AD:test di giorno 30/09/2019',1,28,29,1,4,'test'),
      (3,'prova','tst',NULL,2,8,5,1,10,NULL),
      (4,'v','vvvv','vvvvv',1,2,34,1,11,'vvvv');

    /*
        Insert colletions_samples records
    */
    INSERT INTO `collections_samples` (`id`, `sample_id`, `collection_id`)
    VALUES
      (3,5,1),(4,6,1),(5,2,1),(6,1,2),(7,3,2),(8,7,2),
      (10,4,1),(11,4,1),(12,4,1),(13,4,1),(14,4,1),
      (15,1,2),(16,8,3),(17,10,3);
