apiVersion: v1
kind: Service
metadata:
    name: sample-be-service
    namespace: sample
spec:
    type: ClusterIP # eventualmente usa loadBalancer per prendere l'IP metto il loadbalancer e quindi lo chiamo da usalo solo keycloak
    ports:
    - port: 9092
    selector:
        app: sample-be

# TODO:

      # APP_SHIPMENTSERVICE: "http://shipmentService:9091"
      # APP_BIOBANKSERVICE: "http://biobankService:9093"
      # APP_DONORSERVICE: "http://donorService:9095"