apiVersion: v1
kind: ConfigMap
metadata:
  name: shipment-mysql-config # arbitrary name
  namespace: biobanksprec
data: # the actual contents - key-value pairs
  mysql-url: shipment-db-service # service we're going to creare for mongdb application
  initdb.sql: |
    -- MySQL dump 10.13  Distrib 5.7.38, for Linux (x86_64)
    --
    -- Host: localhost    Database: shipment_db
    -- ------------------------------------------------------
    -- Server version	5.7.38

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    --
    -- Table structure for table `shipment_boxes`
    --

    DROP TABLE IF EXISTS `shipment_boxes`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `shipment_boxes` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `box_id` varchar(255) DEFAULT NULL,
      `location_id` int(11) DEFAULT NULL,
      `location_path` varchar(255) DEFAULT NULL,
      `name` varchar(255) DEFAULT NULL,
      `shipment_id` int(11) DEFAULT NULL,
      `status_id` int(11) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FK8d84srippnpmp1kbd70l98ymb` (`shipment_id`),
      KEY `FK938y9uodoa9qn3uuhdriminyc` (`status_id`),
      CONSTRAINT `FK8d84srippnpmp1kbd70l98ymb` FOREIGN KEY (`shipment_id`) REFERENCES `shipments` (`id`),
      CONSTRAINT `FK938y9uodoa9qn3uuhdriminyc` FOREIGN KEY (`status_id`) REFERENCES `static_shipments_boxes_status` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `shipment_boxes`
    --

    --
    -- Table structure for table `shipments`
    --

    DROP TABLE IF EXISTS `shipments`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `shipments` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `_from` varchar(255) DEFAULT NULL,
      `note` varchar(255) DEFAULT NULL,
      `received_at` varchar(255) DEFAULT NULL,
      `tracking_number` varchar(255) DEFAULT NULL,
      `condition_id` int(11) DEFAULT NULL,
      `status_id` int(11) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FK6oi6mbtvq08ht0r1vu09uqdmn` (`condition_id`),
      KEY `FKk8rey4lwbisc9s7sdmmna5wle` (`status_id`),
      CONSTRAINT `FK6oi6mbtvq08ht0r1vu09uqdmn` FOREIGN KEY (`condition_id`) REFERENCES `static_shipments_condition` (`id`),
      CONSTRAINT `FKk8rey4lwbisc9s7sdmmna5wle` FOREIGN KEY (`status_id`) REFERENCES `static_shipments_status` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `shipments`
    --

    --
    -- Table structure for table `static_shipments_boxes_status`
    --

    DROP TABLE IF EXISTS `static_shipments_boxes_status`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `static_shipments_boxes_status` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `static_shipments_boxes_status`
    --

    --
    -- Table structure for table `static_shipments_condition`
    --

    DROP TABLE IF EXISTS `static_shipments_condition`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `static_shipments_condition` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `static_shipments_condition`
    --

    --
    -- Table structure for table `static_shipments_status`
    --

    DROP TABLE IF EXISTS `static_shipments_status`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `static_shipments_status` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `static_shipments_status`
    --

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

    -- Dump completed on 2022-07-17 14:12:58

    /*
    Insert static_shipments_status records
    */
    INSERT INTO `static_shipments_status` (`id`, `name`)
    VALUES (1,'Shipment Acquired'), (2,'Temporary Stored'),
        (3,'Temporary Stored + Documents'),(4,'Completed');
    /*
        Insert static_shipments_conditions records
    */
    INSERT INTO `static_shipments_condition` (`id`, `name`)
    VALUES (1,'Good Conditions'), (2,'Not Good Conditions');
    /*
        Insert shipments records
    */
    INSERT INTO `shipments` (`id`, `_from`, `tracking_number`, `received_at`, `status_id`, `condition_id`, `note`)
    VALUES
      (1,'ospedale tal de tali','123456789','2019-08-08 07:00:00',2,1,'bla bla'),
      (2,'Garibaldi','34567123456','1996-12-31 16:45:00',1,1,NULL),
      (3,'Garibaldi','ab-34rgt67','2003-09-26 19:59:00',1,1,'sssss-1-35:0978/90');
    /*
        Insert static_shipments_boxes_status records
    */
    INSERT INTO `static_shipments_boxes_status` (`id`, `name`)
    VALUES (1,'Stored. Ready to be processed'),(2,'Completed');
    /*
        Insert shipments_boxes records
    */
    INSERT INTO `shipment_boxes` (`id`, `shipment_id`, `box_id`, `name`, `location_id`, `location_path`, `status_id`)
    VALUES
      (1,1,'B49A89329BB',NULL,9,'Freezer 1/Division 1/Drawer 1/Slot 3',1),
      (2,2,'B7135B8BD1B',NULL,7,'Freezer 1/Division 1/Drawer 1/Slot 1',1),
      (3,3,'B065E4EDBC8',NULL,7,'Freezer 1/Division 1/Drawer 1/Slot 1',1);
