apiVersion : apps/v1
kind: Deployment
metadata:
  name: shipment-be
  namespace: shipment
  labels:
    app: shipment-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipment-be
  template:
    metadata:
      labels:
        app: shipment-be
    spec:
      containers:
        - name: shipment-be
          image: khalld/shipment:latest
          ports:
          - containerPort: 9091
          env:
          - name: 'SPRING_DATASOURCE_USERNAME'
            value: 'admin'
          - name: 'SPRING_DATASOURCE_PASSWORD'
            value: 'admin'
          - name: 'SERVER_PORT'
            value: '9091'
          - name: 'MYSQL_HOST'
            value: '192.168.63.15'
          # - name: 'KEYCLOAK_HOST'
          #   value: 'TODO:'
          # TODO:
          - name: 'BIOBANK_HOST'
            value: 'localhost'
          - name: 'SAMPLE_HOST'
            value: 'localhost'