apiVersion : apps/v1
kind: Deployment
metadata:
  name: shipment-be
  namespace: shipment # è lo stesso namespace da utilizzare nei service
  labels:
    app: shipment-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipment-be
  template:
    metadata:
      labels:
        app: shipment-be
    spec:
      # necessario se immagini private
      # imagePullSecrets:
      #   - name: acr-secret-cs
      containers:
        - name: shipment-be
          image: khalld/shipment:latest
          ports:
          - containerPort: 9091
          env:
          - name: 'SERVER_PORT'
            value: '9091'
          - name: 'MYSQL_HOST'
            value: 'shipment_db'


# TODO:
      #             APP_SAMPLESERVICE: "sample-service.shipment:9092"
      # APP_BIOBANKSERVICE: "http://biobankService:9093"
