apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  # echo -n text | base64
  mysql-user: YWRtaW4K      # admin
  mysql-password: YWRtaW4K  # admin
  mysql-root-pwd: cm9vdAo=  # root