# here there are deploy & service of mysql

apiVersion: apps/v1
kind: Deployment
metadata:
  name: donor-mysql-deployment
  # you can give any k8s component a label
  # are key/value apirs that are attached to k8s resoruces
  # identifier, which should be meaningful and relevant to users
  # but i possible share the same label. For PODS is required
  labels:
    app: donor-mysql
spec: # deploy specific specification
  replicas: 1 # how many pods want to create. 1 'cause is a Db
  # identify a set of resources
  selector:
    # match all pods match with labels ...
    matchLabels:
      # use app when you want to develop your application [best practice]
      app: donor-mysql
  template: # Blueprint for Pods defined by template. Is a configuration for pod
    metadata:
      labels:
        app: donor-mysql
    spec:
      containers: # list of containers used to create by pod
      - name: donor-db
        image: mysql:5.7
        ports:
        - containerPort: 3360
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-pwd
        - name: MYSQL_DATABASE
          value: donor_db
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password  
---
apiVersion: v1
kind: Service
metadata:
  name: donor-db-service # nome relativo a quello di configuraizone
spec:
  selector:
    app: donor-mysql  # select pods to forward the request to ...
  ports:
    - protocol: TCP
      port: 3360 # service port
      targetPort: 3360 # containerPort of deployment